{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "solmManageParamConfigRequest",
	"type": "object",
	"properties": {
		"msgAuthDetails": {
			"type": "object",
			"$ref": "#/definitions/msgAuthDetails"
		},
		"solmManageParamConfigList": {
			"type": "array",
			"minItems": 1,
			"items": {
				"$ref": "#/definitions/solmManageParamConfigList"
			}
		}
	},
	"required": [
		"msgAuthDetails",
		"solmManageParamConfigList"
	],
	"additionalProperties": false,
	"definitions": {
		"msgAuthDetails": {
			"type": "object",
			"properties": {
				"clientNo": {
					"type": "integer"
				},
				"authKey": {
					"type": "string"
				},
				"requestDateTime": {
					"type": "string"
				},
				"signatureValue": {
					"type": "string"
				},
				"signatureVersion": {
					"type": "string"
				},
				"ariaAccountID": {
					"type": "string"
				},
				"ariaAccountNo": {
					"type": "integer"
				},
				"userID": {
					"type": "string"
				}
			},
			"required": [
				"clientNo",
				"requestDateTime",
				"signatureValue",
				"signatureVersion",
				"ariaAccountID",
				"ariaAccountNo",
				"userID"
			],
			"additionalProperties": false
		},
		"solmManageParamConfigList": {
			"type": "object",
			"properties": {
				"solmManageParamConfigAction": {
					"$ref": "#/definitions/solmManageParamConfigAction"
				},
				"solmManageParamConfigInfo": {
					"$ref": "#/definitions/solmManageParamConfigInfo"
				}
			},
			"required": [
				"solmManageParamConfigAction",
				"solmManageParamConfigInfo"
			]
		},
		"solmManageParamConfigAction": {
			"type": "object",
			"properties": {
				"actionCode": {
					"type": "string",
					"enum": [
						"MODIFY",
						"REMOVE"
					]
				}
			},
			"required": [
				"actionCode"
			]
		},
		"solmManageParamConfigInfo": {
			"type": "object",
			"properties": {
				"paramID": {
					"type": "string"
				},
				"paramDefaulted": {
					"type": "boolean"
				},
				"solmManageParamConfigValues": {
					"type": "array",
					"minItems": 1,
					"items": {
						"$ref": "#/definitions/solmManageParamConfigValues"
					}
				}
			},
			"required": [
				"paramID",
				"paramDefaulted"
			]
		},
		"solmManageParamConfigValues": {
			"type": "object",
			"properties": {
				"paramValue": {
					"type": "string"
				}
			},
			"required": [
				"paramValue"
			]
		}
	}
}